#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Employee")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EmployeeConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INT_DisplayCalRecord")]
	public ISingleResult<sp_INT_DisplayCalRecordResult> sp_INT_DisplayCalRecord([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((ISingleResult<sp_INT_DisplayCalRecordResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INT_UpdateCalRecord")]
	public int sp_INT_UpdateCalRecord([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTime", DbType="VarChar(50)")] string startTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReturnTime", DbType="VarChar(50)")] string returnTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="Int")] System.Nullable<int> category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubCategory", DbType="Int")] System.Nullable<int> subCategory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="Text")] string comment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edited_By", DbType="Int")] System.Nullable<int> edited_By)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, startDate, endDate, startTime, returnTime, category, subCategory, comment, edited_By);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INT_DeletePersonalRecord")]
	public int sp_INT_DeletePersonalRecord([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_By", DbType="Int")] System.Nullable<int> deleted_By)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, deleted_By);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INT_AddCalRecord")]
	public int sp_INT_AddCalRecord([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employee_ID", DbType="Int")] System.Nullable<int> employee_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTime", DbType="VarChar(50)")] string startTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReturnTime", DbType="VarChar(50)")] string returnTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="Int")] System.Nullable<int> category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubCategory", DbType="Int")] System.Nullable<int> subCategory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="VarChar(50)")] string comment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Created_By", DbType="Int")] System.Nullable<int> created_By)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employee_ID, startDate, endDate, startTime, returnTime, category, subCategory, comment, created_By);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INT_CurStatus")]
	public ISingleResult<sp_INT_CurStatusResult> sp_INT_CurStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TheDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> theDate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), theDate);
		return ((ISingleResult<sp_INT_CurStatusResult>)(result.ReturnValue));
	}
}

public partial class sp_INT_DisplayCalRecordResult
{
	
	private System.Nullable<System.DateTime> _StartDate;
	
	private System.Nullable<System.DateTime> _EndDate;
	
	private string _StartTime;
	
	private string _ReturnTime;
	
	private System.Nullable<int> _Category;
	
	private System.Nullable<int> _SubCategory;
	
	private string _cc_Category;
	
	private string _cs_SubCategory;
	
	private string _Comment;
	
	public sp_INT_DisplayCalRecordResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> StartDate
	{
		get
		{
			return this._StartDate;
		}
		set
		{
			if ((this._StartDate != value))
			{
				this._StartDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> EndDate
	{
		get
		{
			return this._EndDate;
		}
		set
		{
			if ((this._EndDate != value))
			{
				this._EndDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="VarChar(50)")]
	public string StartTime
	{
		get
		{
			return this._StartTime;
		}
		set
		{
			if ((this._StartTime != value))
			{
				this._StartTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReturnTime", DbType="VarChar(50)")]
	public string ReturnTime
	{
		get
		{
			return this._ReturnTime;
		}
		set
		{
			if ((this._ReturnTime != value))
			{
				this._ReturnTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="Int")]
	public System.Nullable<int> Category
	{
		get
		{
			return this._Category;
		}
		set
		{
			if ((this._Category != value))
			{
				this._Category = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategory", DbType="Int")]
	public System.Nullable<int> SubCategory
	{
		get
		{
			return this._SubCategory;
		}
		set
		{
			if ((this._SubCategory != value))
			{
				this._SubCategory = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cc_Category", DbType="VarChar(50)")]
	public string cc_Category
	{
		get
		{
			return this._cc_Category;
		}
		set
		{
			if ((this._cc_Category != value))
			{
				this._cc_Category = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cs_SubCategory", DbType="VarChar(50)")]
	public string cs_SubCategory
	{
		get
		{
			return this._cs_SubCategory;
		}
		set
		{
			if ((this._cs_SubCategory != value))
			{
				this._cs_SubCategory = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Comment
	{
		get
		{
			return this._Comment;
		}
		set
		{
			if ((this._Comment != value))
			{
				this._Comment = value;
			}
		}
	}
}

public partial class sp_INT_CurStatusResult
{
	
	private string _LastName;
	
	private string _FirstName;
	
	private System.Nullable<System.DateTime> _StartDate;
	
	private System.Nullable<System.DateTime> _EndDate;
	
	private string _StartTime;
	
	private string _ReturnTime;
	
	private string _cc_Category;
	
	private string _cs_SubCategory;
	
	private string _Comment;
	
	public sp_INT_CurStatusResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this._LastName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this._FirstName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> StartDate
	{
		get
		{
			return this._StartDate;
		}
		set
		{
			if ((this._StartDate != value))
			{
				this._StartDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> EndDate
	{
		get
		{
			return this._EndDate;
		}
		set
		{
			if ((this._EndDate != value))
			{
				this._EndDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="VarChar(50)")]
	public string StartTime
	{
		get
		{
			return this._StartTime;
		}
		set
		{
			if ((this._StartTime != value))
			{
				this._StartTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReturnTime", DbType="VarChar(50)")]
	public string ReturnTime
	{
		get
		{
			return this._ReturnTime;
		}
		set
		{
			if ((this._ReturnTime != value))
			{
				this._ReturnTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cc_Category", DbType="VarChar(50)")]
	public string cc_Category
	{
		get
		{
			return this._cc_Category;
		}
		set
		{
			if ((this._cc_Category != value))
			{
				this._cc_Category = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cs_SubCategory", DbType="VarChar(50)")]
	public string cs_SubCategory
	{
		get
		{
			return this._cs_SubCategory;
		}
		set
		{
			if ((this._cs_SubCategory != value))
			{
				this._cs_SubCategory = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Comment
	{
		get
		{
			return this._Comment;
		}
		set
		{
			if ((this._Comment != value))
			{
				this._Comment = value;
			}
		}
	}
}
#pragma warning restore 1591
