#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LeaveCalendarDB")]
public partial class LeaveCalendarDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public LeaveCalendarDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LeaveCalendarDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LeaveCalendarDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LeaveCalendarDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LeaveCalendarDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LeaveCalendarDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertCalendarRecord")]
	public int spInsertCalendarRecord([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_emp_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> lc_StartDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> lc_EndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_AllDayEvent, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_StartTimeHour, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_StartTimeMinutes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_EndTimeHour, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_EndTimeMinutes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_Leavetype, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_Comment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatNumber", DbType="Int")] System.Nullable<int> repeatNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HowOften", DbType="Int")] System.Nullable<int> howOften)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lc_emp_ID, userID, lc_StartDate, lc_EndDate, lc_AllDayEvent, lc_StartTimeHour, lc_StartTimeMinutes, lc_EndTimeHour, lc_EndTimeMinutes, lc_Leavetype, lc_Comment, repeatNumber, howOften);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDeleteCalendarRecord")]
	public int spDeleteCalendarRecord([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_emp_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lc_ID, lc_emp_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSelectCalendarRecordForEdit")]
	public ISingleResult<spSelectCalendarRecordForEditResult> spSelectCalendarRecordForEdit([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exists", DbType="Int")] ref System.Nullable<int> exists)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lc_ID, exists);
		exists = ((System.Nullable<int>)(result.GetParameterValue(1)));
		return ((ISingleResult<spSelectCalendarRecordForEditResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateCalendarRecord")]
	public int spUpdateCalendarRecord([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_emp_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> lc_StartDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> lc_EndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_AllDayEvent, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_StartTimeHour, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_StartTimeMinutes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_EndTimeHour, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_EndTimeMinutes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lc_Leavetype, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lc_Comment)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lc_ID, lc_emp_ID, lc_StartDate, lc_EndDate, lc_AllDayEvent, lc_StartTimeHour, lc_StartTimeMinutes, lc_EndTimeHour, lc_EndTimeMinutes, lc_Leavetype, lc_Comment);
		return ((int)(result.ReturnValue));
	}
}

public partial class spSelectCalendarRecordForEditResult
{
	
	private int _lc_ID;
	
	private System.Nullable<int> _lc_emp_ID;
	
	private System.Nullable<System.DateTime> _lc_StartDate;
	
	private System.Nullable<System.DateTime> _lc_EndDate;
	
	private System.Nullable<int> _lc_AllDayEvent;
	
	private string _lc_StartTimeHour;
	
	private string _lc_StartTimeMinutes;
	
	private string _lc_EndTimeHour;
	
	private string _lc_EndTimeMinutes;
	
	private System.Nullable<int> _lc_LeaveType;
	
	private string _lc_Comment;
	
	private System.Nullable<int> _lc_Active;
	
	public spSelectCalendarRecordForEditResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_ID", DbType="Int NOT NULL")]
	public int lc_ID
	{
		get
		{
			return this._lc_ID;
		}
		set
		{
			if ((this._lc_ID != value))
			{
				this._lc_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_emp_ID", DbType="Int")]
	public System.Nullable<int> lc_emp_ID
	{
		get
		{
			return this._lc_emp_ID;
		}
		set
		{
			if ((this._lc_emp_ID != value))
			{
				this._lc_emp_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_StartDate", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> lc_StartDate
	{
		get
		{
			return this._lc_StartDate;
		}
		set
		{
			if ((this._lc_StartDate != value))
			{
				this._lc_StartDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_EndDate", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> lc_EndDate
	{
		get
		{
			return this._lc_EndDate;
		}
		set
		{
			if ((this._lc_EndDate != value))
			{
				this._lc_EndDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_AllDayEvent", DbType="Int")]
	public System.Nullable<int> lc_AllDayEvent
	{
		get
		{
			return this._lc_AllDayEvent;
		}
		set
		{
			if ((this._lc_AllDayEvent != value))
			{
				this._lc_AllDayEvent = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_StartTimeHour", DbType="VarChar(50)")]
	public string lc_StartTimeHour
	{
		get
		{
			return this._lc_StartTimeHour;
		}
		set
		{
			if ((this._lc_StartTimeHour != value))
			{
				this._lc_StartTimeHour = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_StartTimeMinutes", DbType="VarChar(50)")]
	public string lc_StartTimeMinutes
	{
		get
		{
			return this._lc_StartTimeMinutes;
		}
		set
		{
			if ((this._lc_StartTimeMinutes != value))
			{
				this._lc_StartTimeMinutes = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_EndTimeHour", DbType="VarChar(50)")]
	public string lc_EndTimeHour
	{
		get
		{
			return this._lc_EndTimeHour;
		}
		set
		{
			if ((this._lc_EndTimeHour != value))
			{
				this._lc_EndTimeHour = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_EndTimeMinutes", DbType="VarChar(50)")]
	public string lc_EndTimeMinutes
	{
		get
		{
			return this._lc_EndTimeMinutes;
		}
		set
		{
			if ((this._lc_EndTimeMinutes != value))
			{
				this._lc_EndTimeMinutes = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_LeaveType", DbType="Int")]
	public System.Nullable<int> lc_LeaveType
	{
		get
		{
			return this._lc_LeaveType;
		}
		set
		{
			if ((this._lc_LeaveType != value))
			{
				this._lc_LeaveType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_Comment", DbType="VarChar(50)")]
	public string lc_Comment
	{
		get
		{
			return this._lc_Comment;
		}
		set
		{
			if ((this._lc_Comment != value))
			{
				this._lc_Comment = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lc_Active", DbType="Int")]
	public System.Nullable<int> lc_Active
	{
		get
		{
			return this._lc_Active;
		}
		set
		{
			if ((this._lc_Active != value))
			{
				this._lc_Active = value;
			}
		}
	}
}
#pragma warning restore 1591
